# Generated by Django 5.0.6 on 2024-07-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('mean', models.FloatField(null=True)),
                ('alpha', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('distribution', models.CharField(default='lognormal', max_length=64)),
                ('pathogen_in_ref', models.CharField(default='unknown', max_length=200)),
                ('notes', models.CharField(default='unknown', max_length=200)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.pathogen')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.reference')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflow', to='source.watersource')),
            ],
        ),
    ]
