# Generated by Django 5.0.6 on 2024-07-27 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
        ('treatment', '0004_alter_logremoval_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='reference',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.reference'),
        ),
    ]
