# Generated by Django 5.0.6 on 2024-07-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_inflow_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='max',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='min',
            field=models.FloatField(default=0),
        ),
    ]
