# Generated by Django 5.0.6 on 2024-08-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_alter_inflow_max_alter_inflow_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='max',
            field=models.FloatField(default=1),
        ),
    ]
