# Generated by Django 3.1.1 on 2020-10-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('pathogen_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathogens', to='qmratool.pathogengroup')),
            ],
        ),
    ]
