# Generated by Django 3.1.7 on 2021-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='volume_per_event',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
