# Generated by Django 3.1.1 on 2020-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
