# Generated by Django 4.1.2 on 2024-04-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qmratool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
