# Generated by Django 3.1.7 on 2021-04-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0002_auto_20210407_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='volume_per_event',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
