# Generated by Django 3.1.1 on 2020-09-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0002_auto_20200928_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='qmratool.user'),
            preserve_default=False,
        ),
    ]
