# Generated by Django 4.1.2 on 2024-04-23 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qmratool", "0002_riskassessment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcewater",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sourcewaters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inflow",
            name="water_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inflow",
                to="qmratool.sourcewater",
            ),
        ),
    ]
