# Generated by Django 3.1.1 on 2020-10-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0002_pathogen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogen',
            name='pathogen',
            field=models.CharField(default='Rota', max_length=64),
        ),
    ]
