# Generated by Django 3.1.1 on 2020-10-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0003_pathogen_pathogen'),
    ]

    operations = [
        migrations.AddField(
            model_name='logremoval',
            name='alpha',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logremoval',
            name='beta',
            field=models.DecimalField(decimal_places=3, default=11, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logremoval',
            name='distribution',
            field=models.CharField(default='uniform', max_length=64),
        ),
        migrations.AddField(
            model_name='logremoval',
            name='mean',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logremoval',
            name='pathogen_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='qmratool.pathogengroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logremoval',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='qmratool.reference'),
            preserve_default=False,
        ),
    ]
