# Generated by Django 3.1.1 on 2020-09-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0003_riskassessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='exposure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='qmratool.exposure'),
        ),
    ]
