# Generated by Django 3.1.1 on 2020-09-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0004_auto_20200928_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qmratool.exposure'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qmratool.sourcewater'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='treatment',
            field=models.ManyToManyField(blank=True, null=True, related_name='treatment', to='qmratool.Treatment'),
        ),
    ]
