# Generated by Django 3.1.1 on 2020-10-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0004_auto_20201015_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='reference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference'),
        ),
    ]
