# Generated by Django 3.1.1 on 2020-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0005_exposure_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logremoval',
            name='alpha',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='logremoval',
            name='beta',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='logremoval',
            name='mean',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
