# Generated by Django 3.1.1 on 2020-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0006_auto_20201015_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='events_per_year',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='use',
            field=models.CharField(max_length=250),
        ),
    ]
