# Generated by Django 3.1.1 on 2020-10-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0008_auto_20201015_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference'),
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mean', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('alpha', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('beta', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('distribution', models.CharField(default='lognormal', max_length=64)),
                ('pathogen_in_ref', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.pathogen')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.sourcewater')),
            ],
        ),
    ]
