# Generated by Django 3.1.1 on 2020-10-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0009_auto_20201018_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infection_to_illness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dalys_per_case', models.DecimalField(decimal_places=6, max_digits=6)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.pathogen')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference')),
            ],
        ),
        migrations.CreateModel(
            name='DoseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestfitmodel', models.CharField(max_length=250)),
                ('k', models.DecimalField(decimal_places=10, max_digits=20)),
                ('alpha', models.DecimalField(decimal_places=10, max_digits=20)),
                ('n50', models.DecimalField(decimal_places=10, max_digits=20)),
                ('hosttype', models.CharField(max_length=250)),
                ('doseunits', models.CharField(max_length=250)),
                ('route', models.CharField(max_length=250)),
                ('response', models.CharField(max_length=250)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.pathogen')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference')),
            ],
        ),
    ]
