# Generated by Django 3.1.1 on 2020-10-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0011_auto_20201018_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='reference',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference'),
        ),
    ]
