# Generated by Django 3.1.1 on 2020-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0012_auto_20201018_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doseresponse',
            name='alpha',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='bestfitmodel',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='doseunits',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='hosttype',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='k',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='n50',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='response',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='doseresponse',
            name='route',
            field=models.CharField(default='unknown', max_length=250),
        ),
    ]
