# Generated by Django 3.1.1 on 2020-10-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0014_auto_20201018_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='alpha',
            field=models.DecimalField(decimal_places=8, default=-100, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='beta',
            field=models.DecimalField(decimal_places=8, default=-100, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='max',
            field=models.DecimalField(decimal_places=8, default=-100, max_digits=20),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='mean',
            field=models.DecimalField(decimal_places=8, default=-100, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='min',
            field=models.DecimalField(decimal_places=8, default=-100, max_digits=20),
        ),
    ]
