# Generated by Django 3.1.1 on 2020-11-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0015_auto_20201018_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='category',
            field=models.CharField(default='wastewater', max_length=64),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='exposure',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='qmratool.Exposure'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='group',
            field=models.CharField(default='wastewater', max_length=64),
        ),
    ]
