# Generated by Django 3.1.1 on 2020-11-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0016_auto_20201101_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='category',
        ),
    ]
