# Generated by Django 3.1.1 on 2020-11-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0017_remove_treatment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposure',
            old_name='use',
            new_name='name',
        ),
        migrations.AddField(
            model_name='exposure',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='qmratool.user'),
            preserve_default=False,
        ),
    ]
