# Generated by Django 3.1.1 on 2020-11-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0018_auto_20201102_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='reference',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, to='qmratool.reference'),
        ),
    ]
