# Generated by Django 3.1.1 on 2020-11-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0019_auto_20201102_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='qmratool.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exposure',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
