# Generated by Django 3.1.1 on 2020-11-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0020_auto_20201107_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logremoval',
            name='reference',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='qmratool.reference'),
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='exposure',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='exposure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='qmratool.exposure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
