# Generated by Django 3.1.1 on 2020-11-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0021_auto_20201110_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='exposure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='qmratool.exposure'),
        ),
    ]
