# Generated by Django 3.1.1 on 2020-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0023_auto_20201110_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='category',
            field=models.CharField(default='waterwater', max_length=64),
        ),
    ]
