# Generated by Django 3.1.1 on 2020-12-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0024_treatment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(default='wastewater', max_length=64),
        ),
    ]
