# Generated by Django 3.1.1 on 2020-12-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0025_auto_20201205_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[('wastewater', 'wastewater'), ('drinking_water', 'drinking water')], default='wastewater', max_length=64),
        ),
    ]
