# Generated by Django 3.1.7 on 2021-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0026_auto_20201205_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='category',
            field=models.CharField(choices=[('wastewater', 'wastewater'), ('drinking_water', 'drinking water'), ('surface_water', 'surface water')], default='wastewater', max_length=64),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
