# Generated by Django 3.1.7 on 2021-03-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0027_auto_20210301_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.ManyToManyField(blank=True, to='qmratool.RiskAssessment')),
            ],
        ),
    ]
