# Generated by Django 3.1.7 on 2021-03-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0028_comparison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparison',
            old_name='ra',
            new_name='risk_assessment',
        ),
    ]
