# Generated by Django 3.1.7 on 2021-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmratool', '0030_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(max_length=20000),
        ),
    ]
