# Generated by Django 5.0.6 on 2024-07-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathogenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathogen_group', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.URLField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rota', max_length=64)),
                ('description', models.TextField(max_length=2000)),
                ('pathogen_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathogens', to='treatment.pathogengroup')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('group', models.CharField(default='wastewater', max_length=64)),
                ('category', models.CharField(choices=[('wastewater', 'wastewater'), ('drinking_water', 'drinking water'), ('surface_water', 'surface water')], default='wastewater', max_length=64)),
                ('description', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('mean', models.FloatField(null=True)),
                ('alpha', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('distribution', models.CharField(default='uniform', max_length=64)),
                ('pathogen_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='treatment.pathogengroup')),
                ('reference', models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='treatment.reference')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='treatment.treatment')),
            ],
        ),
    ]
