# Generated by Django 5.0.6 on 2024-07-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathogen',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
