# Generated by Django 5.0.6 on 2024-07-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_alter_pathogen_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logremoval',
            name='reference',
            field=models.ForeignKey(blank=True, default=51, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logremoval', to='treatment.reference'),
        ),
    ]
