# Generated by Django 5.0.6 on 2024-07-28 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenario', '0001_initial'),
        ('source', '0003_alter_inflow_max_alter_inflow_min'),
        ('treatment', '0004_alter_logremoval_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestfitmodel', models.CharField(default='unknown', max_length=250)),
                ('k', models.FloatField(default=0)),
                ('alpha', models.FloatField(default=0)),
                ('n50', models.FloatField(default=0)),
                ('hosttype', models.CharField(default='unknown', max_length=250)),
                ('doseunits', models.CharField(default='unknown', max_length=250)),
                ('route', models.CharField(default='unknown', max_length=250)),
                ('response', models.CharField(default='unknown', max_length=250)),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.pathogen')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infection_to_illness', models.FloatField()),
                ('dalys_per_case', models.FloatField()),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.pathogen')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.reference')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('exposure', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='scenario.exposurescenario')),
                ('source', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='source.watersource')),
                ('treatment', models.ManyToManyField(blank=True, default=1, related_name='treatments', to='treatment.treatment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_assessment', models.ManyToManyField(blank=True, to='risk_assessment.riskassessment')),
            ],
        ),
    ]
